apiVersion: vpn.netbird.crossplane.io/v1alpha1
kind: NbAccessToken
metadata:
  name: xplaneserviceuseraccesstokentest
spec:
  providerConfigRef:
    name: "netbird-crossplane-provider-config"
  forProvider:
    expires_in: 1
    name: test-token
    user_id: b268c87b-b23c-4b80-ad56-762f04cd19e5
  writeConnectionSecretToRef:
    name: accesstokensecrettest
    namespace: crossplane-system
