apiVersion: vpn.netbird.crossplane.io/v1alpha1
kind: NbAccount
metadata:
  name: xplaneaccounttest
spec:
  managementPolicies: ["Observe"]
  forProvider:
    settings:
      extra:
        peer_approval_enabled: false
      groups_propagation_enabled: true
      jwt_allow_groups:
        - "311982725156307259:techops-admin"
        - "311982725156307259:techops-users"
      jwt_groups_claim_name: "zitadel:grants"
      jwt_groups_enabled: true
      peer_inactivity_expiration: 0
      peer_inactivity_expiration_enabled: false
      peer_login_expiration: 86400
      peer_login_expiration_enabled: true
      regular_users_view_blocked: true
  providerConfigRef:
    name: example
