apiVersion: vpn.netbird.crossplane.io/v1alpha1
kind: NbAccessToken
metadata:
  name: xplaneserviceuseraccesstokentest
spec:
  providerConfigRef:
    name: "netbird-crossplane-provider-config"
  forProvider:
    expires_in: 1
    name: test-token
    user_id: e80879f8-de26-459d-9f97-bf77eebbb108
  writeConnectionSecretToRef:
    name: accesstokensecrettest
    namespace: crossplane-system
