apiVersion: vpn.netbird.crossplane.io/v1alpha1
kind: NbAccount
metadata:
  name: xplaneaccounttest
spec:
  managementPolicies:
    - "Observe"
    - "Update"
    - "Create"
    - "LateInitialize"
  forProvider:
    settings:
      extra:
        network_traffic_logs_enabled: false
        network_traffic_packet_counter_enabled: false
        peer_approval_enabled: false
      groups_propagation_enabled: true
      jwt_allow_groups:
        - 327118187810283563:techops-admin
        - 327118187810283563:techops-users
      jwt_groups_claim_name: zitadel:grants
      jwt_groups_enabled: true
      peer_inactivity_expiration: 0
      peer_inactivity_expiration_enabled: false
      peer_login_expiration: 86400
      peer_login_expiration_enabled: true
      regular_users_view_blocked: true
      routing_peer_dns_resolution_enabled: true

  providerConfigRef:
    name: "netbird-crossplane-provider-config"
