apiVersion: vpn.netbird.crossplane.io/v1alpha1
kind: NbAccessToken
metadata:
  name: xplaneserviceuseraccesstokentest
spec:
  providerConfigRef:
    name: "netbird-crossplane-provider-config"
  forProvider:
    expires_in: 1
    name: test-token
    user_id: decba6d4-cc76-4e1b-ace9-9c021c2e31f3
  writeConnectionSecretToRef:
    name: accesstokensecrettest
    namespace: crossplane-system
