apiVersion: vpn.netbird.crossplane.io/v1alpha1
kind: NbDnsSetting
metadata:
  name: xplanednssettingtest
spec:
  managementPolicies:
    - "Observe"
    - "Update"
    - "Create"
    - "LateInitialize"
  providerConfigRef:
    name: example
  forProvider:
    disabled_management_groups:
      - cvel12smo3bc73brmsvg
