apiVersion: vpn.netbird.crossplane.io/v1alpha1
kind: NbGroup
metadata:
  name: xplanegrouptest
spec:
  forProvider:
    name: xplanegrouptest
  providerConfigRef:
    name: example
---
apiVersion: vpn.netbird.crossplane.io/v1alpha1
kind: NbGroup
metadata:
  name: xplanepeergrouptest
spec:
  forProvider:
    name: xplanepeergrouptest
  providerConfigRef:
    name: example
