apiVersion: vpn.netbird.crossplane.io/v1alpha1
kind: NbNetworkResource
metadata:
  name: xplaneresourcetest
spec:
  forProvider:
    description: "test network resource"
    enabled: true
    name: testnetworkresource
    groups:
      - name: "cc-k8s"
    address: "10.10.10.0/24"
    network_name: ccinfra2

  providerConfigRef:
    name: "netbird-crossplane-provider-config"
