apiVersion: vpn.netbird.crossplane.io/v1alpha1
kind: NbPolicy
metadata:
  name: xplanepolicytest2
spec:
  providerConfigRef:
    name: "netbird-crossplane-provider-config"
  forProvider:
    description: test policy2
    enabled: true
    name: xplanepolicytest2
    rules:
      - name: xplanepolicytestrule2
        action: accept
        bidirectional: false
        description: test rule
        destinations:
          - name: xplanepeergrouptest
        enabled: true
        sources:
          - name: All
        ports: ["80", "443"]
        protocol: tcp
