apiVersion: vpn.netbird.crossplane.io/v1alpha1
kind: NbPolicy
metadata:
  name: xplanepolicytest
spec:
  providerConfigRef:
    name: "netbird-crossplane-provider-config"
  forProvider:
    description: test policy
    enabled: true
    name: xplanepolicytest
    rules:
      - name: xplanepolicytestrule
        action: accept
        bidirectional: true
        description: test rule
        destinations:
          - name: xplanegrouptest
        enabled: true
        port_ranges:
          - start: 180
            end: 300
        protocol: tcp
        sources:
          - name: xplanegrouptest2
