apiVersion: vpn.netbird.crossplane.io/v1alpha1
kind: NbSetupKey
metadata:
  name: xplanesetupkeytest
spec:
  forProvider:
    name: xplanesetupkeytest
    allow_extra_dns_labels: false
    type: reusable
    expires_in: 86400
    revoked: false
    auto_groups:
      - d1vjtdj1l8qc738v57q0
    usage_limit: 0
    ephemeral: false
  providerConfigRef:
    name: "netbird-crossplane-provider-config"
  writeConnectionSecretToRef:
    name: setupkeysecret
    namespace: crossplane-system
