apiVersion: vpn.netbird.crossplane.io/v1alpha1
kind: NbUser
metadata:
  name: xplaneusertest
spec:
  managementPolicies:
    - "Observe"
    - "Update"
    - "Create"
    - "LateInitialize"
  providerConfigRef:
    name: example
  forProvider:
    email: david@infitx.com
    is_service_user: false
---
apiVersion: vpn.netbird.crossplane.io/v1alpha1
kind: NbUser
metadata:
  name: xplaneserviceusertest
spec:
  providerConfigRef:
    name: example
  forProvider:
    name: testserviceuser
    is_service_user: true
    role: admin
    auto_groups: []
