# apiVersion: netbird.infitx.org/v1alpha1
# kind: PostConfig
# metadata:
#   name: example-post-config
#   namespace: default
# spec:
#   parameters:
#     ccClusterName: "fry-cluster-name"
#     environments:
#       - "frydev"
#       - "fryqa"
#     setupKey:
#       name: "fry-setup-key-name"
#       namespace: "default"
#       gwSetupKeySecretKey: "fry-gw-setup-key-secret-key"
#       buildSetupKeySecretKey: "fry-build-setup-key-secret-key"
#     zitadelProjectId: 312158817523600227
#     groupNames:
#       admin: techops-admin
#       externalAccess: techops-users
#   providerConfigsRef:
#     netbirdProviderConfigName: "netbird-crossplane-provider-config"
#     k8sProviderConfigName: "kubernetes-crossplane-provider-config"
#   managementPolicies:
#     - "*"
# ---
# apiVersion: sc.infitx.org/v1alpha1
# kind: NBOperatorInstall
# metadata:
#   name: sc-nboperatorinstall
#   namespace: default
# spec:
#   parameters:
#     serviceUserName: testserviceuser
#     accessTokenExpiresInDays: 5
#     nbManagmentURI: https://netbird.ccinfra.drpp-onprem.global/
#     operatorHelmVersion: 0.1.6
#     operatorNamespace: netbird
#     operatorArgoAppName: nb-op
#     operatorArgoAppSourceURL: https://github.com/mojaloop/iac-modules/gitops/applications/base/netbird-operator
#     operatorArgoAppSourceRevision: "feature/storage-cluster"
#     localAccessTokenSecretName: nb-op-access-token
#     localAccessTokenSecretNamespace: default
#   providerConfigsRef:
#     netbirdProviderConfigName: "netbird-provider-config"
#     ccK8sProviderName: "kubernetes-provider"
#     scK8sProviderName: "sc-kubernetes-provider"
#   managementPolicies:
#     - "*"
---
apiVersion: nb.mojaloop.io/v1alpha1
kind: NetbirdEnvConfig
metadata:
  name: netbird-env-config
  namespace: test
spec:
  parameters:
    pushSecret:
      esoPushSecret: false
    envProperties:
      setupKey:
        name: test-k8s-nodes-key
        namespace: test
        vaultSecretPath: test/netbird_k8s_setup_key
      groupNames:
        ccNetworkResource: cc-internal
        scNetworkResource: sc-internal
        envK8sNodes: test-k8s-nodes
    managedService:
      enabled: false
      setupKey:
        name: test-ms-gw-key
        namespace: test
        vaultSecretPath: test/netbird_ms_gw_setup_key
      groupNames:
        managedSvc: test-ms-gw
  providerConfigsRef:
    netbirdProviderConfigName: "netbird-crossplane-provider-config"
    k8sProviderConfigName: "kubernetes-provider"
  managementPolicies:
    - "*"
