apiVersion: netbird.infitx.org/v1alpha1
kind: PostConfig
metadata:
  name: example-post-config
  namespace: default
spec:
  parameters:
    ccClusterName: "fry-cluster-name"
    environments:
      - "frydev"
      - "fryqa"
    setupKey:
      name: "fry-setup-key-name"
      namespace: "default"
      gwSetupKeySecretKey: "fry-gw-setup-key-secret-key"
      buildSetupKeySecretKey: "fry-build-setup-key-secret-key"
    zitadelProjectId: 312158817523600227
    groupNames:
      admin: techops-admin
      externalAccess: techops-users
  providerConfigsRef:
    netbirdProviderConfigName: "netbird-crossplane-provider-config"
    k8sProviderConfigName: "kubernetes-crossplane-provider-config"
  managementPolicies:
    - "*"
