apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: debug-config
spec:
  args:
    - --debug
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: netbird-crossplane-provider
spec:
  package: ghcr.io/infitx-org/netbird-crossplane-provider:v0.0.5-rc6
  controllerConfigRef:
    name: debug-config
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: kubernetes-crossplane-provider
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.15.0
  controllerConfigRef:
    name: debug-config
