apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: debug-config
spec:
  args:
    - --debug
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: netbird-crossplane-provider
spec:
  package: ghcr.io/infitx-org/netbird-crossplane-provider:v0.0.5-rc2
  controllerConfigRef:
    name: debug-config
