name: Publish Provider

on:
  push:
    branches:
      - '**' # TOOD: To be change to run just on tags
  pull_request: {}
  workflow_dispatch: {}

env:
  # Common versions
  GO_VERSION: '1.23'
  GOLANGCI_VERSION: 'v1.54.0'
  DOCKER_BUILDX_VERSION: 'v0.9.1'

  # Registry/Org names
  CROSSPLANE_REGORG: 'ghcr.io/infitx-org'

jobs:
  publish-provider:
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: ${{ env.DOCKER_BUILDX_VERSION }}
          install: true

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Fetch History
        run: git fetch --prune --unshallow

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Find the Go Build Cache
        id: go
        run: echo "cachedir=$(make go.cachedir)" >> $GITHUB_ENV

      - name: Cache the Go Build Cache
        uses: actions/cache@v3
        with:
          path: ${{ env.cachedir }}
          key: ${{ runner.os }}-build-publish-provider-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-build-publish-provider-

      - name: Cache Go Dependencies
        uses: actions/cache@v3
        with:
          path: .work/pkg
          key: ${{ runner.os }}-pkg-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-pkg-

      - name: Download Go Modules
        run: make modules.download modules.check

      - name: Build Provider
        run: make -j2 build.all
        env:
          # We're using docker buildx, which doesn't actually load the images it
          # builds by default. Specifying --load does so.
          BUILD_ARGS: "--load"

      - name: Publish Provider
        run: |
          make -j XPKG_REG_ORGS="${{ env.CROSSPLANE_REGORG }}" XPKG_REG_ORGS_NO_PROMOTE="${{ env.CROSSPLANE_REGORG }}" publish
